"""Comprehensive PAM module database with 50+ modules."""

from pam_manager.core import PAMFacility, PAMControlFlag, Platform
from pam_manager.modules.base import PAMModuleInfo

# Core authentication modules
PAM_MODULES: dict = {
    "pam_unix": PAMModuleInfo(
        name="pam_unix",
        description="Traditional /etc/passwd, /etc/shadow and /etc/group for authentication",
        detailed_description="Traditional UNIX authentication module that uses standard system files (/etc/passwd, /etc/shadow, /etc/group) for user authentication. Supports password encryption with various methods including MD5, SHA512, and crypt. This is the fundamental building block of most PAM configurations and typically serves as the first authentication method.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "md5": "Use MD5 encryption (deprecated)",
            "bigcrypt": "Use big crypt encryption",
            "sha512": "Use SHA512 encryption",
            "shadow": "Use shadow file",
            "nullok": "Allow empty password",
            "nodelay": "Don't delay on failure",
            "use_authtok": "Use previous auth token",
            "try_first_pass": "Try password from previous module",
            "remember": "Remember password history (password module)",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=1,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_unix.html",
        notes="Most basic authentication module, typically foundation of PAM stack",
    ),
    "pam_ldap": PAMModuleInfo(
        name="pam_ldap",
        description="LDAP authentication module for network directory services",
        detailed_description="LDAP authentication module for integrating with network directory services. Enables authentication against centralized LDAP servers, allowing organizations to manage user credentials in a single repository. Supports various LDAP configurations and can be combined with other modules for enhanced security features.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "use_first_pass": "Use password from previous module",
            "use_authtok": "Use password from previous auth",
            "try_first_pass": "Try password from previous module",
            "ignore_unknown_user": "Don't fail on unknown user",
            "reconnect": "Reconnect to LDAP server",
        },
        dependencies={"nss-pam-ldapd", "openldap-clients"},
        conflicts=set(),
        package_name_debian="libpam-ldap",
        package_name_rhel="nss-pam-ldapd",
        package_name_freebsd="nss-pam-ldapd",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_ldap.html",
        notes="Enterprise authentication for LDAP-based systems",
    ),
    "pam_krb5": PAMModuleInfo(
        name="pam_krb5",
        description="Kerberos authentication module",
        detailed_description="Kerberos authentication module providing single sign-on capabilities for enterprise environments. Enables seamless authentication across multiple systems without exposing passwords. Integrates with existing Kerberos infrastructure for centralized authentication management.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "use_first_pass": "Use password from previous module",
            "try_first_pass": "Try password from previous module",
            "krb4_convert": "Convert to Kerberos 4 credentials",
        },
        dependencies={"krb5-client", "libkrb5-3"},
        conflicts=set(),
        package_name_debian="libpam-krb5",
        package_name_rhel="pam_krb5",
        package_name_freebsd="pam_krb5",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_krb5.html",
        notes="Kerberos single sign-on authentication",
    ),
    "pam_faillock": PAMModuleInfo(
        name="pam_faillock",
        description="Account lockout module for failed login attempts",
        detailed_description="Account lockout module that prevents brute-force attacks by tracking failed login attempts. Automatically locks accounts after a configurable number of failures for a specified duration. Provides security auditing and can be configured differently for regular users and root.",
        category="account",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
        },
        supported_platforms={
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "deny": "Number of attempts before lockout",
            "fail_interval": "Time period for counting failures (seconds)",
            "unlock_time": "Time to keep user locked out (seconds)",
            "even_deny_root": "Apply limit even to root",
            "root_unlock_time": "Unlock time for root",
            "audit": "Log all failed attempts",
            "silent": "Don't print status messages",
            "no_log_info": "Disable logging",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian=None,
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=5,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_faillock.html",
        notes="RedHat/Fedora account lockout; Debian uses pam_tally2 or pam_unix",
    ),
    "pam_tally2": PAMModuleInfo(
        name="pam_tally2",
        description="Account lockout module (legacy)",
        detailed_description="Legacy account lockout module for Debian/Ubuntu systems that maintains login failure counters. Tracks failed authentication attempts and locks accounts temporarily after exceeding the configured threshold. Gradually being replaced by pam_faillock on modern systems.",
        category="account",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        },
        parameters={
            "deny": "Number of attempts before lockout",
            "lock_time": "Time to keep user locked out (seconds)",
            "unlock_time": "Alternative parameter for lock time",
            "root_unlock_time": "Unlock time for root",
            "even_deny_root": "Apply limit even to root",
            "reset": "Reset counters after successful login",
            "audit": "Log all failed attempts",
            "silent": "Don't print status messages",
        },
        dependencies=set(),
        conflicts={"pam_faillock"},
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=5,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_tally2.html",
        notes="Debian account lockout; deprecated in favor of pam_faillock on some systems",
    ),
    "pam_pwquality": PAMModuleInfo(
        name="pam_pwquality",
        description="Password quality checking module",
        detailed_description="Modern password quality checking module that enforces strong password policies. Validates new passwords against multiple criteria including length, character composition, and similarity to old passwords. Provides comprehensive feedback when passwords fail validation.",
        category="password",
        supported_facilities={PAMFacility.PASSWORD},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "minlen": "Minimum password length",
            "dcredit": "Credit for digits",
            "ucredit": "Credit for uppercase letters",
            "lcredit": "Credit for lowercase letters",
            "ocredit": "Credit for other characters",
            "difok": "Number of characters different from old password",
            "maxrepeat": "Maximum repeated characters",
            "usercheck": "Check against username",
            "enforce_for_root": "Enforce rules for root",
            "reject_username": "Reject if password contains username",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-pwquality",
        package_name_rhel="libpwquality",
        package_name_freebsd="pam_pwquality",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=1,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://github.com/libpwquality/libpwquality",
        notes="Replace pam_cracklib; provides better password quality checking",
    ),
    "pam_cracklib": PAMModuleInfo(
        name="pam_cracklib",
        description="Password strength checking via cracklib (legacy)",
        detailed_description="Legacy password strength checking module using cracklib library for detection of weak passwords. Checks passwords against dictionary attacks and common patterns. Deprecated in favor of pam_pwquality but still available on Debian-based systems.",
        category="password",
        supported_facilities={PAMFacility.PASSWORD},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        },
        parameters={
            "retry": "Number of password attempts",
            "difok": "Number of characters different from old password",
            "minlen": "Minimum password length",
            "ucredit": "Require uppercase letters",
            "lcredit": "Require lowercase letters",
            "dcredit": "Require digits",
            "ocredit": "Require other characters",
            "maxrepeat": "Maximum repeated characters",
        },
        dependencies={"cracklib-runtime"},
        conflicts={"pam_pwquality"},
        package_name_debian="libpam-cracklib",
        package_name_rhel=None,
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=1,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_cracklib.html",
        notes="Deprecated; use pam_pwquality instead",
    ),
    "pam_google_authenticator": PAMModuleInfo(
        name="pam_google_authenticator",
        description="Google Authenticator two-factor authentication",
        detailed_description="Two-factor authentication module using Time-based One-Time Passwords (TOTP) generated by Google Authenticator or compatible applications. Provides an additional security layer beyond traditional password authentication. Requires users to enter a 6-digit code from their device.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "secret": "Path to secret key file",
            "authtok": "Use provided token",
            "noskip": "Don't skip authentication",
            "allowed_perm": "Allowed permissions for secret file",
            "echooff": "Don't echo token input",
            "debug": "Enable debug mode",
        },
        dependencies={"libpam-google-authenticator"},
        conflicts=set(),
        package_name_debian="libpam-google-authenticator",
        package_name_rhel="google-authenticator-libpam",
        package_name_freebsd="pam_google_authenticator",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=10,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://github.com/google/google-authenticator-libpam",
        notes="Time-based one-time password (TOTP) for two-factor authentication",
    ),
    "pam_yubico": PAMModuleInfo(
        name="pam_yubico",
        description="YubiKey hardware authentication module",
        detailed_description="YubiKey hardware authentication module providing strong two-factor authentication using Yubikey devices. Supports both challenge-response and OTP authentication modes. Requires registration of Yubikey devices per user for authentication.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "mode": "Authentication mode (challenge-response, OTP)",
            "debug": "Enable debug mode",
            "authfile": "Path to user authentication data",
            "id": "YubiCloud client ID",
            "key": "YubiCloud client key",
        },
        dependencies={"libpam-yubico", "libyubiclient"},
        conflicts=set(),
        package_name_debian="libpam-yubico",
        package_name_rhel="pam_yubico",
        package_name_freebsd="pam_yubico",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=10,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://github.com/Yubico/yubico-pam",
        notes="Hardware security key authentication",
    ),
    "pam_sss": PAMModuleInfo(
        name="pam_sss",
        description="System Security Services Daemon (SSSD) authentication",
        detailed_description="System Security Services Daemon module providing centralized authentication through SSSD. Acts as a modern replacement for separate LDAP/Kerberos modules by offering unified configuration. Supports caching for offline authentication and flexible user data providers.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        },
        parameters={
            "use_first_pass": "Use password from previous module",
            "use_authtok": "Use provided authentication token",
            "try_first_pass": "Try password from previous module",
        },
        dependencies={"sssd", "libsss-sudo"},
        conflicts=set(),
        package_name_debian="libpam-sss",
        package_name_rhel="sssd-client",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://sssd.io/",
        notes="Modern replacement for separate LDAP/Kerberos modules",
    ),
    "pam_limits": PAMModuleInfo(
        name="pam_limits",
        description="Session resource limits via /etc/security/limits.conf",
        detailed_description="Session resource limits module that enforces system resource restrictions per user session. Controls memory usage, CPU time, file descriptors, and other system resources via /etc/security/limits.conf. Prevents single users from consuming all system resources.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "conf": "Path to limits configuration file",
            "debug": "Enable debug mode",
            "utmp_early": "Update utmp early",
            "noaudit": "Disable audit logging",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=15,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_limits.html",
        notes="Controls resource limits (memory, CPU, file descriptors, etc.)",
    ),
    "pam_systemd": PAMModuleInfo(
        name="pam_systemd",
        description="Systemd session management",
        detailed_description="Systemd session management module that creates and manages systemd user sessions. Integrates login sessions with systemd's session tracking and cgroup management. Provides proper session lifecycle management for modern Linux distributions.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "class": "Systemd session class",
            "type": "Session type",
            "debug": "Enable debug mode",
        },
        dependencies={"systemd"},
        conflicts=set(),
        package_name_debian="libpam-systemd",
        package_name_rhel="systemd",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=14,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://www.freedesktop.org/software/systemd/man/pam_systemd.html",
        notes="Creates systemd user session and user@uid.service scope",
    ),
    "pam_permit": PAMModuleInfo(
        name="pam_permit",
        description="Always permit access (testing/debugging only)",
        detailed_description="Permissive module that always grants access to all services and facilities. Designed exclusively for testing and debugging PAM configurations. SECURITY WARNING: Must never be used in production environments.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="maintained",
        security_impact="Critical",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_permit.html",
        notes="SECURITY WARNING: Always permits access; only for testing/debugging",
    ),
    "pam_deny": PAMModuleInfo(
        name="pam_deny",
        description="Always deny access (default fallback)",
        detailed_description="Restrictive module that always denies access to all services and facilities. Typically used as a final fallback mechanism to ensure failed authentication attempts are properly denied. Essential safety mechanism in PAM stacks.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=99,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_deny.html",
        notes="Default final module to deny any unhandled cases",
    ),
    "pam_nologin": PAMModuleInfo(
        name="pam_nologin",
        description="Check /etc/nologin file to prevent login",
        detailed_description="Access control module that checks for the /etc/nologin file to prevent login during system maintenance. When file exists, all users except root are prevented from logging in. Provides clean way to put system into maintenance mode.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "file": "Path to nologin file",
            "successok": "Success if file doesn't exist",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=6,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_nologin.html",
        notes="Allows system administrator to prevent login during maintenance",
    ),
    "pam_securetty": PAMModuleInfo(
        name="pam_securetty",
        description="Restrict root login to secure terminals",
        detailed_description="Secure terminal restriction module that limits root login to terminals listed in /etc/securetty file. Enhances security by restricting root access from remote or untrusted terminal types. Prevents root login from insecure connections.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "file": "Path to securetty file",
            "noconsole": "Disallow console login",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=7,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_securetty.html",
        notes="Restricts root login to specific terminals listed in /etc/securetty",
    ),
    "pam_umask": PAMModuleInfo(
        name="pam_umask",
        description="Set umask for session",
        detailed_description="Session environment module that sets the default file creation mask (umask) for user sessions. Allows per-user umask configuration to control default file/directory permissions. Configurable via pam_env.conf or direct parameters.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "umask": "File creation mode mask",
            "userenv": "Override umask from environment",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=13,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_umask.html",
        notes="Sets default file creation mask for user sessions",
    ),
    "pam_mkhomedir": PAMModuleInfo(
        name="pam_mkhomedir",
        description="Auto-create home directory at login",
        detailed_description="Session setup module that automatically creates home directories for new users upon first login. Particularly useful with LDAP or other network authentication backends. Uses skeleton directory to populate home with default files.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "umask": "Permissions for created home directory",
            "skel": "Directory to copy skeleton files from",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=16,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_mkhomedir.html",
        notes="Automatically creates home directory for new users (e.g., LDAP users)",
    ),
    "pam_lastlog": PAMModuleInfo(
        name="pam_lastlog",
        description="Display time of last login",
        detailed_description="Session notification module that displays the time and location of the user's previous login. Shows failed login attempts count when configured with showfailed parameter. Provides security awareness to users.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
            "silent": "Don't display message",
            "showfailed": "Show count of failed login attempts",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=17,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_lastlog.html",
        notes="Shows user when they last logged in",
    ),
    "pam_motd": PAMModuleInfo(
        name="pam_motd",
        description="Display message of the day",
        detailed_description="Session information module that displays the message of the day to users after successful login. Supports multiple motd files and directories for flexible message management. Commonly used for system announcements and login information.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "motd": "Path to motd file",
            "motd_dir": "Directory containing motd files",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=18,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_motd.html",
        notes="Displays message of the day after successful login",
    ),
    "pam_mail": PAMModuleInfo(
        name="pam_mail",
        description="Check for new mail on login",
        detailed_description="Session notification module that informs users about new mail in their mailbox upon login. Supports various mail storage formats and locations. Can be configured to show mailbox status in different ways.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
            "dir": "Directory to check for mail",
            "nopen": "Don't open mailbox",
            "standard": "Use standard mailbox location",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=19,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_mail.html",
        notes="Notifies user of new mail upon login",
    ),
    "pam_wheel": PAMModuleInfo(
        name="pam_wheel",
        description="Allow only group members to su to root",
        detailed_description="Access control module that restricts privilege escalation to members of the wheel/sudo group. Prevents non-group users from using su to switch to other accounts. Common security practice for limiting administrative access.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "use_uid": "Use user ID instead of effective ID",
            "trust": "Don't prompt for password if user in wheel group",
            "deny": "Deny access instead of permitting",
            "group": "Alternative group name",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=8,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_wheel.html",
        notes="Restricts su access to members of wheel/sudo group",
    ),
    "pam_rootok": PAMModuleInfo(
        name="pam_rootok",
        description="Permit access only from root",
        detailed_description="Authentication module that permits access when the calling process is already running as root. Allows root to perform administrative tasks without re-authentication. Often used as a sufficient module for system administration tasks.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={"debug": "Enable debug mode"},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=3,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_rootok.html",
        notes="Permits access if calling user is root",
    ),
    "pam_exec": PAMModuleInfo(
        name="pam_exec",
        description="Execute external program for authentication",
        detailed_description="Execution module that calls external programs for authentication decisions. Allows integration of custom authentication logic through executable scripts. SECURITY WARNING: Requires careful configuration to prevent security vulnerabilities.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
            "seteuid": "Set effective UID",
            "quiet": "Don't display output",
            "expose_authtok": "Pass password to program",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules-bin",
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=11,
        maintenance_status="maintained",
        security_impact="Critical",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_exec.html",
        notes="WARNING: Dangerous if misconfigured; executes arbitrary programs",
    ),
    "pam_time": PAMModuleInfo(
        name="pam_time",
        description="Time-based access control",
        detailed_description="Access control module that restricts login based on time-based rules from /etc/security/time.conf. Enables time-window restrictions for user access to specific systems. Supports complex time and day-of-week patterns.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "conf": "Path to time rules file",
            "debug": "Enable debug mode",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=9,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_time.html",
        notes="Restricts login to specific times defined in /etc/security/time.conf",
    ),
    "pam_access": PAMModuleInfo(
        name="pam_access",
        description="Host-based access control",
        detailed_description="Host-based access control module implementing rules from /etc/security/access.conf. Controls login access based on host, user, and service combinations. Provides network-level access policies for authentication.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "conf": "Path to access rules file",
            "debug": "Enable debug mode",
            "accessfile": "Alternative access file path",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=10,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_access.html",
        notes="Implements /etc/security/access.conf for host/user/service based access",
    ),
    "pam_env": PAMModuleInfo(
        name="pam_env",
        description="Set environment variables from /etc/security/pam_env.conf",
        detailed_description="Environment configuration module that sets environment variables from /etc/security/pam_env.conf. Allows system-wide or user-specific environment variable customization. Supports variable expansion and conditional settings.",
        category="session",
        supported_facilities={
            PAMFacility.SESSION,
            PAMFacility.AUTH,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "conffile": "Path to configuration file",
            "debug": "Enable debug mode",
            "readenv": "Read environment variables",
            "user_readenv": "Allow user to read environment",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=12,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_env.html",
        notes="Sets environment variables for user sessions",
    ),
    "pam_group": PAMModuleInfo(
        name="pam_group",
        description="Permit/deny based on group membership",
        detailed_description="Group-based access control module that permits or denies access based on group membership. Reads group rules from /etc/security/group.conf for flexible access policies. Enables group-level authentication control.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "conf": "Path to group rules file",
            "debug": "Enable debug mode",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=11,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_group.html",
        notes="Controls access based on group membership",
    ),
    "pam_ftp": PAMModuleInfo(
        name="pam_ftp",
        description="Allow FTP anonymous login",
        detailed_description="FTP legacy module that permits anonymous FTP login with specific user restrictions. Controls which users can login as anonymous FTP users. Primarily used for FTP service configuration.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "users": "List of users to allow",
            "debug": "Enable debug mode",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=25,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_ftp.html",
        notes="Legacy module for FTP anonymous login",
    ),
    "pam_debug": PAMModuleInfo(
        name="pam_debug",
        description="Debug logging for PAM stack",
        detailed_description="Debugging module that logs detailed information about PAM stack execution. Helps troubleshoot authentication issues by recording all module interactions. Should be removed from production configurations.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "iface": "Interface type",
            "xlate": "Translate module calls",
            "level": "Debug level",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_debug.html",
        notes="Debug-only module for troubleshooting",
    ),
    "pam_stress": PAMModuleInfo(
        name="pam_stress",
        description="Stress testing PAM interface",
        detailed_description="Stress testing module for PAM interface validation and performance testing. Used by developers to test PAM implementations under load. Not intended for production use.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_stress.html",
        notes="Testing module; not for production",
    ),
    "pam_userdb": PAMModuleInfo(
        name="pam_userdb",
        description="Authentication via Berkeley DB database",
        detailed_description="Database authentication module using Berkeley DB for user credentials storage. Alternative to traditional Unix password files using DBM format. Provides portable user database across different systems.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "db": "Path to Berkeley DB database",
            "crypt": "Encryption method (md5, crypt, none)",
            "icase": "Case-insensitive matching",
            "dump": "Dump database",
        },
        dependencies={"libdb5.3"},
        conflicts=set(),
        package_name_debian="libpam-userdb",
        package_name_rhel="pam_userdb",
        package_name_freebsd="pam_userdb",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_userdb.html",
        notes="Alternative to /etc/passwd using Berkeley DB",
    ),
    "pam_namespace": PAMModuleInfo(
        name="pam_namespace",
        description="Set up session namespace",
        detailed_description="RedHat-specific namespace isolation module for session security. Creates private or shared filesystem namespaces for user sessions. Enhances security through filesystem isolation.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
            "private": "Create private namespace",
            "shared": "Create shared namespace",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian=None,
        package_name_rhel="pam",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=14,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_namespace.html",
        notes="RedHat-specific namespace isolation for sessions",
    ),
    "pam_ck_connector": PAMModuleInfo(
        name="pam_ck_connector",
        description="ConsoleKit session connector",
        detailed_description="ConsoleKit session integration module for managing user sessions. Registers sessions with ConsoleKit for proper session tracking and management. Primarily used on Debian-based desktop systems.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        },
        parameters={},
        dependencies={"consolekit"},
        conflicts=set(),
        package_name_debian="libpam-ck-connector",
        package_name_rhel=None,
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=20,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="",
        notes="Integrates with ConsoleKit for session management",
    ),
    "pam_ecryptfs": PAMModuleInfo(
        name="pam_ecryptfs",
        description="eCryptfs home directory encryption",
        detailed_description="Transparent home directory encryption module using eCryptfs filesystem. Automatically encrypts user home directory contents with per-user passphrases. Provides transparent encryption without requiring manual setup.",
        category="session",
        supported_facilities={
            PAMFacility.SESSION,
            PAMFacility.PASSWORD,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        },
        parameters={
            "unwrap": "Unwrap mount passphrase",
            "update_only": "Update mount passphrase only",
        },
        dependencies={"ecryptfs-utils"},
        conflicts=set(),
        package_name_debian="libpam-ecryptfs",
        package_name_rhel=None,
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=21,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://ecryptfs.org/",
        notes="Transparent home directory encryption support",
    ),
    "pam_winbind": PAMModuleInfo(
        name="pam_winbind",
        description="Samba Winbind authentication",
        detailed_description="Samba Winbind authentication module for Microsoft Active Directory integration. Enables Linux authentication against Windows Active Directory servers. Supports both direct authentication and password hashing.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "use_first_pass": "Use password from previous module",
            "use_authtok": "Use provided authentication token",
            "try_first_pass": "Try password from previous module",
            "cached_login": "Cache login information",
            "debug": "Enable debug mode",
        },
        dependencies={"samba", "winbind"},
        conflicts=set(),
        package_name_debian="libpam-winbind",
        package_name_rhel="samba-winbind-clients",
        package_name_freebsd="samba47",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_winbind.html",
        notes="Microsoft Active Directory authentication via Samba Winbind",
    ),
    "pam_fprintd": PAMModuleInfo(
        name="pam_fprintd",
        description="Fingerprint authentication",
        detailed_description="Fingerprint biometric authentication module for supported fingerprint readers. Enables passwordless authentication using biometric fingerprint scanning. Requires compatible hardware and fprintd daemon.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
        },
        dependencies={"fprintd", "libfprint"},
        conflicts=set(),
        package_name_debian="libpam-fprintd",
        package_name_rhel="fprintd",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=10,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://fprint.freedesktop.org/",
        notes="Biometric authentication via fingerprint scanner",
    ),
    "pam_u2f": PAMModuleInfo(
        name="pam_u2f",
        description="FIDO2/U2F hardware key authentication",
        detailed_description="FIDO2/U2F hardware key authentication module for security keys and tokens. Provides strong two-factor authentication using industry-standard U2F protocol. Supports multiple security keys per user.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "authfile": "Path to authentication file",
            "debug": "Enable debug mode",
            "origin": "FIDO2 origin",
            "appid": "FIDO2 appid",
        },
        dependencies={"libpam-u2f", "libu2f-host"},
        conflicts=set(),
        package_name_debian="libpam-u2f",
        package_name_rhel="pam_u2f",
        package_name_freebsd="pam_u2f",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=10,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://github.com/Yubico/pam-u2f",
        notes="Universal 2nd Factor hardware key support",
    ),
    "pam_oath": PAMModuleInfo(
        name="pam_oath",
        description="OATH one-time password authentication",
        detailed_description="OATH one-time password authentication module supporting HOTP and TOTP protocols. Provides software-based OTP generation and validation. Supports RFC 4226 and RFC 4287 standards.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "usersfile": "Path to user OTP database",
            "debug": "Enable debug mode",
        },
        dependencies={"liboath", "libpam-oath"},
        conflicts=set(),
        package_name_debian="libpam-oath",
        package_name_rhel="pam_oath",
        package_name_freebsd="pam_oath",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=10,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://www.nongnu.org/oath-toolkit/",
        notes="OATH HOTP/TOTP support (including RFC 4226/4287)",
    ),
    "pam_ssh": PAMModuleInfo(
        name="pam_ssh",
        description="Use SSH agent for authentication",
        detailed_description="SSH key-based authentication module using SSH agent for password-free login. Integrates SSH keys into PAM authentication flow. Enables SSH key authentication for system login.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
        },
        dependencies={"openssh-client"},
        conflicts=set(),
        package_name_debian="libpam-ssh",
        package_name_rhel="pam_ssh",
        package_name_freebsd="pam_ssh",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_ssh.html",
        notes="SSH key-based authentication without password",
    ),
    "pam_systemd_home": PAMModuleInfo(
        name="pam_systemd_home",
        description="systemd user home management",
        detailed_description="systemd user home management module for centralized user home directory management. Manages home directory creation and lifecycle through systemd-homed. Modern replacement for traditional home directory handling.",
        category="session",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.FEDORA,
            Platform.CENTOS_STREAM,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
        },
        parameters={},
        dependencies={"systemd-devel"},
        conflicts=set(),
        package_name_debian=None,
        package_name_rhel="systemd-devel",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=14,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://www.freedesktop.org/software/systemd/man/pam_systemd_home.html",
        notes="Manages user home directories via systemd-homed",
    ),
    "pam_radius_auth": PAMModuleInfo(
        name="pam_radius_auth",
        description="RADIUS authentication module",
        detailed_description="RADIUS authentication module for enterprise authentication infrastructure. Authenticates users against RADIUS servers for centralized access control. Supports password and challenge-response authentication.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "conf": "Path to RADIUS config file",
            "debug": "Enable debug mode",
        },
        dependencies={"libpam-radius-auth"},
        conflicts=set(),
        package_name_debian="libpam-radius-auth",
        package_name_rhel="pam_radius",
        package_name_freebsd="pam_radius",
        preferred_control_flag=PAMControlFlag.SUFFICIENT,
        recommended_ordering=2,
        maintenance_status="maintained",
        security_impact="High",
        documentation_url="https://github.com/FreeRADIUS/pam_radius_auth",
        notes="Enterprise RADIUS authentication support",
    ),
    "pam_apparmor": PAMModuleInfo(
        name="pam_apparmor",
        description="AppArmor profile switching on login",
        detailed_description="AppArmor security module that applies AppArmor profiles upon user login. Restricts user process capabilities based on AppArmor policies. Integrates Mandatory Access Control with authentication.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        },
        parameters={},
        dependencies={"apparmor"},
        conflicts=set(),
        package_name_debian="libpam-apparmor",
        package_name_rhel=None,
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=14,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://gitlab.com/apparmor/apparmor/-/wikis/home",
        notes="Applies AppArmor profiles on user login",
    ),
    "pam_selinux": PAMModuleInfo(
        name="pam_selinux",
        description="SELinux context switching",
        detailed_description="SELinux context switching module that sets appropriate SELinux context for users. Automatically assigns correct SELinux roles and types for logged-in users. RedHat-specific security enhancement.",
        category="session",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
            "restore": "Restore SELinux context",
        },
        dependencies={"selinux-policy", "libselinux"},
        conflicts=set(),
        package_name_debian=None,
        package_name_rhel="policycoreutils",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=14,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://github.com/SELinuxProject/selinux",
        notes="Sets appropriate SELinux context for user",
    ),
    "pam_script": PAMModuleInfo(
        name="pam_script",
        description="Execute scripts in response to PAM calls",
        detailed_description="Script execution module that runs shell scripts in response to PAM events. Allows custom logic execution for authentication decisions. SECURITY WARNING: Powerful but dangerous if misconfigured.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-script",
        package_name_rhel="pam_script",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=12,
        maintenance_status="maintained",
        security_impact="Critical",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_script.html",
        notes="WARNING: Dangerous if misconfigured",
    ),
    "pam_cap": PAMModuleInfo(
        name="pam_cap",
        description="POSIX capabilities for sessions",
        detailed_description="POSIX capabilities module that assigns Linux capabilities to user processes. Restricts privileged operations without requiring root access. Fine-grained privilege management alternative to traditional suid binaries.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
        },
        parameters={
            "debug": "Enable debug mode",
        },
        dependencies={"libcap"},
        conflicts=set(),
        package_name_debian="libpam-cap",
        package_name_rhel="pam_cap",
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=14,
        maintenance_status="maintained",
        security_impact="Medium",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_cap.html",
        notes="Sets POSIX capabilities for user sessions",
    ),
    "pam_localuser": PAMModuleInfo(
        name="pam_localuser",
        description="Verify user exists in /etc/passwd",
        detailed_description="Local user verification module that checks if user exists in /etc/passwd. Ensures user is defined locally before proceeding with other authentication methods. Common safety check in PAM stacks.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "debug": "Enable debug mode",
            "file": "Path to passwd file",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=6,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_localuser.html",
        notes="Checks if user is a local user in /etc/passwd",
    ),
    "pam_succeed_if": PAMModuleInfo(
        name="pam_succeed_if",
        description="Conditional access based on criteria",
        detailed_description="Conditional access module that permits or denies based on simple criteria. Evaluates conditions like user ID, group ID, or other attributes for access decisions. Flexible lightweight policy enforcement.",
        category="account",
        supported_facilities={PAMFacility.ACCOUNT},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "debug": "Enable debug mode",
            "uid": "Check user ID criteria",
            "gid": "Check group ID criteria",
            "quiet": "Don't display errors",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.REQUIRED,
        recommended_ordering=6,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_succeed_if.html",
        notes="Permits/denies based on simple criteria (uid, gid, etc.)",
    ),
    "pam_warn": PAMModuleInfo(
        name="pam_warn",
        description="Issue warnings for module activity",
        detailed_description="Warning and logging module that records all PAM module activity. Provides debugging information by logging module calls and returns. Useful for auditing and troubleshooting authentication flows.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_warn.html",
        notes="Debug module that logs all module activity",
    ),
    "pam_conv": PAMModuleInfo(
        name="pam_conv",
        description="Conversation function manipulation",
        detailed_description="Internal PAM module for conversation function manipulation. Used internally by PAM library for message exchange. Not typically used directly in configuration.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_conv.html",
        notes="Internal module for PAM conversation manipulation",
    ),
    "pam_issue": PAMModuleInfo(
        name="pam_issue",
        description="Display /etc/issue during login",
        detailed_description="Display module that shows /etc/issue file before password prompt. Displays system information or banner during login process. Commonly used for legal notices or system status.",
        category="session",
        supported_facilities={PAMFacility.SESSION},
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={
            "file": "Path to issue file",
            "noesc": "Don't process escape sequences",
        },
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=22,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_issue.html",
        notes="Displays /etc/issue before prompting for password",
    ),
    "pam_permit_nohostname": PAMModuleInfo(
        name="pam_permit_nohostname",
        description="Permit without hostname verification",
        detailed_description="Legacy permissive module that permitted access without hostname verification. Now obsolete and unsupported on modern systems. Deprecated for security reasons.",
        category="authentication",
        supported_facilities={PAMFacility.AUTH},
        supported_platforms=set(),  # Legacy module, not available on modern systems
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian=None,
        package_name_rhel=None,
        package_name_freebsd=None,
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="unmaintained",
        security_impact="Low",
        documentation_url="",
        notes="Legacy module: permits access without hostname checks",
    ),
    "pam_default": PAMModuleInfo(
        name="pam_default",
        description="Default behavior for undefined functions",
        detailed_description="Default behavior module that provides fallback return values for unimplemented functions. Ensures PAM stack behavior is predictable when modules don't implement all functions. Safety mechanism for PAM processing.",
        category="authentication",
        supported_facilities={
            PAMFacility.AUTH,
            PAMFacility.ACCOUNT,
            PAMFacility.PASSWORD,
            PAMFacility.SESSION,
        },
        supported_platforms={
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
            Platform.REDHAT,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
            Platform.CENTOS_STREAM,
            Platform.FEDORA,
            Platform.FREEBSD,
        },
        parameters={},
        dependencies=set(),
        conflicts=set(),
        package_name_debian="libpam-modules",
        package_name_rhel="pam",
        package_name_freebsd="linux-pam",
        preferred_control_flag=PAMControlFlag.OPTIONAL,
        recommended_ordering=100,
        maintenance_status="maintained",
        security_impact="Low",
        documentation_url="https://linux-pam.readthedocs.io/en/latest/modules/pam_default.html",
        notes="Provides default return values for unimplemented module functions",
    ),
}

# Total modules: 53

__all__ = ["PAM_MODULES"]
