"""PAM Renderer - Generates PAM configuration files from policies."""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
from datetime import datetime
from pathlib import Path

from pam_manager.core import PAMControlFlag, PAMFacility, Platform
from pam_manager.engine import PolicyEngine
from pam_manager.modules import ModuleRegistry
from pam_manager.policy import PolicyModel


@dataclass(frozen=True)
class PamFileLine:
    """Represents a single line in PAM configuration."""

    facility: PAMFacility  # auth, account, password, session
    control: PAMControlFlag  # required, optional, sufficient, etc.
    module: str  # pam_unix, pam_pwquality, etc.
    arguments: List[str]  # Module arguments

    def to_string(self) -> str:
        """Convert to PAM file line format.

        Returns:
            PAM configuration line
        """
        facility_str = self.facility.name.lower()
        control_str = self.control.value
        args_str = " ".join(self.arguments) if self.arguments else ""

        if args_str:
            return f"{facility_str} {control_str} {self.module} {args_str}"
        return f"{facility_str} {control_str} {self.module}"


@dataclass(frozen=True)
class PamFileConfig:
    """Configuration for a PAM file."""

    name: str  # e.g., "common-auth" or "system-auth"
    path: Path  # Full path to the file
    lines: List[PamFileLine]  # Configuration lines
    includes: List[str] = None  # Files to include
    comments: List[str] = None  # Header comments

    def __post_init__(self) -> None:
        """Initialize includes and comments if not provided."""
        if self.includes is None:
            object.__setattr__(self, "includes", [])
        if self.comments is None:
            object.__setattr__(
                self,
                "comments",
                [
                    f"# PAM configuration for {self.name}",
                    "# Generated by PAM Manager",
                    f"# {datetime.now().isoformat()}",
                ],
            )


class PamRenderer:
    """Generates PAM configuration files from policies."""

    def __init__(self, platform: Platform = None) -> None:
        """Initialize renderer.

        Args:
            platform: Target platform for PAM paths
        """
        self.platform = platform or Platform.UBUNTU
        self.registry = ModuleRegistry()
        self.engine = PolicyEngine(platform)
        self._pam_paths = self._get_pam_paths()

    def _get_pam_paths(self) -> Dict[str, Path]:
        """Get PAM configuration paths for platform.

        Returns:
            Dictionary of PAM paths by name
        """
        debian_paths = {
            "common-auth": Path("/etc/pam.d/common-auth"),
            "common-account": Path("/etc/pam.d/common-account"),
            "common-password": Path("/etc/pam.d/common-password"),
            "common-session": Path("/etc/pam.d/common-session"),
            "common-session-noninteractive": Path("/etc/pam.d/common-session-noninteractive"),
        }

        fedora_paths = {
            "system-auth": Path("/etc/pam.d/system-auth"),
            "password-auth": Path("/etc/pam.d/password-auth"),
            "fingerprint-auth": Path("/etc/pam.d/fingerprint-auth"),
            "smartcard-auth": Path("/etc/pam.d/smartcard-auth"),
        }

        if self.platform in (
            Platform.DEBIAN,
            Platform.UBUNTU,
            Platform.LINUX_MINT,
            Platform.KALI_LINUX,
        ):
            return debian_paths
        if self.platform in (
            Platform.FEDORA,
            Platform.REDHAT,
            Platform.CENTOS_STREAM,
            Platform.ROCKY_LINUX,
            Platform.ALMA_LINUX,
        ):
            return fedora_paths

        return {}

    def render_policy(
        self, modules: List[str]
    ) -> Dict[str, PamFileConfig]:
        """Render modules into PAM file configurations.

        Args:
            modules: List of module names

        Returns:
            Dictionary mapping file names to PamFileConfig
        """
        configs = {}

        # Group modules by facility
        facility_modules: Dict[PAMFacility, List[str]] = {}
        for module_name in modules:
            module_info = self.engine.get_module_info(module_name)
            if module_info.get("found"):
                facilities = module_info.get("facilities", [])
                for facility_str in facilities:
                    # Parse facility string
                    facility = self._parse_facility(facility_str)
                    if facility:
                        if facility not in facility_modules:
                            facility_modules[facility] = []
                        facility_modules[facility].append(module_name)

        # Create PAM file for each facility
        file_map = {
            PAMFacility.AUTH: "common-auth" if self.platform == Platform.UBUNTU else "system-auth",
            PAMFacility.ACCOUNT: "common-account" if self.platform == Platform.UBUNTU else "system-auth",
            PAMFacility.PASSWORD: "common-password" if self.platform == Platform.UBUNTU else "password-auth",
            PAMFacility.SESSION: "common-session" if self.platform == Platform.UBUNTU else "system-auth",
        }

        for facility, file_key in file_map.items():
            if facility in facility_modules:
                lines = self._create_pam_lines(facility, facility_modules[facility])
                if lines:
                    config = PamFileConfig(
                        name=file_key,
                        path=self._pam_paths.get(file_key, Path(f"/etc/pam.d/{file_key}")),
                        lines=lines,
                    )
                    configs[file_key] = config

        return configs

    def _create_pam_lines(
        self, facility: PAMFacility, modules: List[str]
    ) -> List[PamFileLine]:
        """Create PAM lines for facility modules.

        Args:
            facility: PAM facility
            modules: List of module names

        Returns:
            List of PAM lines
        """
        lines = []

        for module_name in modules:
            module_info = self.registry.get_module(module_name)
            if not module_info:
                continue

            # Get control flag
            control = PAMControlFlag[module_info.preferred_control_flag.name]

            # Create line
            line = PamFileLine(
                facility=facility,
                control=control,
                module=module_name,
                arguments=[],  # Would parse from module config
            )
            lines.append(line)

        return lines

    def _parse_facility(self, facility_str: str) -> Optional[PAMFacility]:
        """Parse facility string to PAMFacility enum.

        Args:
            facility_str: Facility name string

        Returns:
            PAMFacility enum or None
        """
        try:
            if isinstance(facility_str, PAMFacility):
                return facility_str
            return PAMFacility[facility_str.upper()]
        except (KeyError, AttributeError):
            return None

    def render_to_string(self, config: PamFileConfig) -> str:
        """Render PAM file configuration to string.

        Args:
            config: PamFileConfig

        Returns:
            Formatted PAM configuration string
        """
        lines = []

        # Add comments
        if config.comments:
            lines.extend(config.comments)
            lines.append("")

        # Add includes
        if config.includes:
            for include in config.includes:
                lines.append(f"@include {include}")
            lines.append("")

        # Add configuration lines
        for line in config.lines:
            lines.append(line.to_string())

        lines.append("")  # Trailing newline

        return "\n".join(lines)

    def save_to_file(self, config: PamFileConfig, dry_run: bool = True) -> bool:
        """Save PAM configuration to file.

        Args:
            config: PamFileConfig
            dry_run: If True, don't actually write to file

        Returns:
            True if successful
        """
        try:
            content = self.render_to_string(config)

            if not dry_run:
                # Backup existing file
                if config.path.exists():
                    backup_path = Path(str(config.path) + ".bak")
                    config.path.rename(backup_path)

                # Write new file
                config.path.write_text(content)

            return True
        except Exception as e:
            return False

    def validate_rendered_policy(self, configs: Dict[str, PamFileConfig]) -> Dict:
        """Validate rendered PAM configurations.

        Args:
            configs: Dictionary of PamFileConfig

        Returns:
            Validation results dictionary
        """
        issues = []
        warnings = []

        for file_name, config in configs.items():
            # Check for empty files
            if not config.lines:
                warnings.append(f"File {file_name} has no configuration lines")

            # Check for required facilities
            facilities = set(line.facility for line in config.lines)
            if PAMFacility.AUTH not in facilities and "auth" in file_name:
                issues.append(f"File {file_name} missing auth facility")

        return {
            "valid": len(issues) == 0,
            "issues": issues,
            "warnings": warnings,
        }

    def get_deployment_script(self, configs: Dict[str, PamFileConfig]) -> str:
        """Generate shell script to deploy PAM configuration.

        Args:
            configs: Dictionary of PamFileConfig

        Returns:
            Bash script content
        """
        script_lines = [
            "#!/bin/bash",
            "# PAM Configuration Deployment Script",
            f"# Generated: {datetime.now().isoformat()}",
            f"# Platform: {self.platform.name}",
            "",
            "set -e",  # Exit on error
            "",
            "# Backup existing PAM files",
            "mkdir -p /etc/pam.d/backup",
            "",
        ]

        for file_name, config in configs.items():
            script_lines.append(f"# Deploy {file_name}")
            script_lines.append(
                f'cp "{config.path}" "/etc/pam.d/backup/{file_name}.$(date +%s)"'
            )
            script_lines.append(f'cat > "{config.path}" << \'EOF\'')
            script_lines.append(self.render_to_string(config).rstrip())
            script_lines.append("EOF")
            script_lines.append("")

        script_lines.extend(
            [
                "echo 'PAM configuration deployed successfully'",
                "echo 'Backup files saved to /etc/pam.d/backup'",
            ]
        )

        return "\n".join(script_lines)

    def generate_policy_report(self, configs: Dict[str, PamFileConfig]) -> str:
        """Generate human-readable report of rendered policy.

        Args:
            configs: Dictionary of PamFileConfig

        Returns:
            Report string
        """
        report_lines = [
            "=" * 60,
            "PAM RENDERER REPORT",
            "=" * 60,
            f"Platform: {self.platform.name}",
            f"Generated: {datetime.now().isoformat()}",
            "",
            "FILES TO BE GENERATED/MODIFIED:",
            "-" * 60,
        ]

        for file_name, config in configs.items():
            report_lines.append(f"\nFile: {config.path}")
            report_lines.append(f"Lines: {len(config.lines)}")
            report_lines.append("Content:")

            for line in config.lines:
                report_lines.append(f"  {line.to_string()}")

        # Validation
        validation = self.validate_rendered_policy(configs)
        report_lines.extend(
            [
                "",
                "-" * 60,
                "VALIDATION RESULTS:",
                f"Valid: {validation['valid']}",
            ]
        )

        if validation["warnings"]:
            report_lines.append("Warnings:")
            for warning in validation["warnings"]:
                report_lines.append(f"  ⚠️  {warning}")

        if validation["issues"]:
            report_lines.append("Issues:")
            for issue in validation["issues"]:
                report_lines.append(f"  ❌ {issue}")

        report_lines.append("=" * 60)

        return "\n".join(report_lines)


__all__ = ["PamRenderer", "PamFileLine", "PamFileConfig"]
